USE [master]
GO

/****** Object:  Database [demos]    Script Date: 6/27/2014 10:44:03 AM ******/
CREATE DATABASE [demos]
-- ON  PRIMARY 
--( NAME = N'demos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\demos.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
-- LOG ON 
--( NAME = N'demos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\demos_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [demos] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [demos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [demos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [demos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [demos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [demos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [demos] SET ARITHABORT OFF 
GO

ALTER DATABASE [demos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [demos] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [demos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [demos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [demos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [demos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [demos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [demos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [demos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [demos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [demos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [demos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [demos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [demos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [demos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [demos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [demos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [demos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [demos] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [demos] SET  MULTI_USER 
GO

ALTER DATABASE [demos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [demos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [demos] SET  READ_WRITE 
GO


